### ISSUE TITLE
Allow multiple directions at once

### ISSUE THREAD

**Issue by andrew** [andrew/webflight-onscreen-keyboard#1]
Non-conflicting buttons should be able to be pressed at the same time, i.e. forwards and up and left, but not forwards and backwards.

If one button is click again it should untoggle it, leaving other valid buttons still pressed, if all buttons are turned off it should return to hovering.

cc @escapologyBB

**Comment by robotsandcake** [comment]
Could we hadd a "Safety Mode" such that if I were to press forward and then did nothing, the drone would only travel on for a few seconds before stopping. This might be especially useful when travelling higher and higher!

Use case: I have muscle spasms which means that occasionally my finger comes off the button and needs to be put back on by a grown-up, watching the drone sail away might not be a great day out.  :-)

**Comment by andrew** [comment]
@escapologyBB I've moved the safety mode into a seperate issue: https://github.com/andrew/webflight-onscreen-keyboard/issues/2

**Comment by robotsandcake** [comment]
Cool, so should I put any new ideas like this as separate issues and mark them as Enhancements?  Still getting to grips with how  Github works you see.

**Comment by andrew** [comment]
@escapologyBB exactly, each new feature or bug as a separate issue unless they are closely related, labels as you see fit.

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
