### ISSUE TITLE
Config error in the readme

### ISSUE THREAD

**Issue by robotsandcake** [andrew/webflight-onscreen-keyboard#3]
Hi,

Just a quick note to say that in the README the instructions say to use the following in the config:

```
   , "onscreen-keyboard"  // overlays on-screen keyboard onto the video window
```

But I could only get it to work when I used the following name for the plugin:

```
   , "webflight-onscreen-keyboard"  // overlays on-screen keyboard onto the video window
```

Not sure if anyone else is seeing this, but this is the only way I could get it to work.

Thanks!

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
